services:
  # Servicio de la aplicación PHP
  web:
    build: .
    container_name: sistemasescolar_web
    ports:
      - "8080:80"
    # volumes:
    #   - .:/var/www/html
    #   - ./php/uploads:/var/www/html/php/uploads
    depends_on:
      - db
    # environment:
    #   - APACHE_DOCUMENT_ROOT=/var/www/html
    networks:
      - sistemasescolar_network

  # Servicio de la base de datos MySQL/MariaDB
  db:
    image: mariadb:10.4
    container_name: sistemasescolar_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mi_proyecto
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./mi_proyecto.sql:/docker-entrypoint-initdb.d/mi_proyecto.sql
    networks:
      - sistemasescolar_network

  # Servicio phpMyAdmin (opcional, para administrar la base de datos)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sistemasescolar_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    depends_on:
      - db
    networks:
      - sistemasescolar_network

# Volúmenes persistentes
volumes:
  db_data:

# Red personalizada
networks:
  sistemasescolar_network:
    driver: bridge
